---
- hosts: all
  become: yes
  tasks:
   - name: update apt cache and install nginx
     apt:
      name: nginx
      state: latest
      update_cache: yes

   - name: copy website files to server location
     copy:
      src: abc.com
      dest: /var/www
      mode: preserve

   - name: aaply nginx template
     template:
      src: nginx.conf.j2
      dest: /etc/nginx/sites-available/default
     notify: restart nginx

  handlers:
   - name: restart nginx
     service:
      name: nginx
      state: restarted
